export const themeCopy = {
  accueillant: {
    eyebrow: "Une écoute attentive, une réalisation qui te ressemble",
    title: "Ton idée mérite une solution pensée à partir de ta réalité.",
    intro: "Je prends le temps de comprendre ton activité, tes ambitions et les personnes auxquelles tu t’adresses, puis je transforme cette matière en une solution claire et fidèle à ton univers.",
  },
  affirme: {
    eyebrow: "De l’ambition à une solution qui prend position",
    title: "Donnons à ton idée la structure et l’élan pour exister.",
    intro: "Tu apportes la vision. Je la challenge, la structure et la transforme en expérience numérique singulière, prête à convaincre tes utilisateurs comme tes futurs partenaires.",
  },
  minimaliste: {
    eyebrow: "Une méthode précise au service de ton projet",
    title: "Clarifier. Concevoir. Développer la bonne solution.",
    intro: "Chaque décision répond à un besoin identifié. Je cadre le périmètre, organise les priorités et développe une solution cohérente, maintenable et capable d’évoluer.",
  },
};

export const offers = [
  {
    id: "maturer-idee",
    group: "product",
    step: "2.1",
    name: "Faire mûrir",
    title: "Exploration et feuille de route",
    price: "Package à partir de 750 €*",
    description: "Pour questionner une idée, identifier ce qui doit encore être décidé et construire une trajectoire réaliste.",
    details: ["Exploration du besoin et des publics", "Questions fonctionnelles et techniques", "Première version et priorités", "Feuille de route : financement, conception, développement, tests et lancement"],
    voices: {
      accueillant: {
        description: "Pour faire grandir une idée avec des questions concrètes, poser les décisions importantes et dessiner un chemin réaliste.",
        result: "Tu repars avec une vision plus claire du projet, des choix à faire et de la prochaine étape.",
      },
      affirme: {
        description: "Pour challenger une idée, tester sa cohérence et la transformer en projet défendable devant de futurs partenaires.",
        result: "Une première version priorisée et une trajectoire que tu peux expliquer, financer et construire.",
      },
      minimaliste: {
        description: "Analyse de l’idée, identification des inconnues et organisation des étapes avant conception.",
        result: "Livrable : synthèse des décisions, première version et feuille de route.",
      },
    },
  },
  {
    id: "presence-essentielle",
    group: "website",
    step: "1.1",
    name: "Présenter",
    title: "Présence essentielle",
    price: "À partir de 1 400 €*",
    description: "Pour présenter une activité lorsque l’identité, les contenus et le parcours attendu sont déjà définis.",
    details: ["Structure courte et parcours principal", "Intégration des contenus fournis", "Responsive, formulaire et SEO essentiel", "Mise en ligne et repères de prise en main"],
    voices: {
      accueillant: {
        description: "Pour offrir à une activité déjà bien définie un espace clair, rassurant et simple à parcourir.",
        result: "Exemple : une indépendante possède déjà son identité, ses textes et ses images, puis souhaite les réunir dans un site professionnel.",
      },
      affirme: {
        description: "Pour installer rapidement une présence crédible lorsque le message, l’identité et les contenus sont prêts.",
        result: "Exemple : une activité définie qui a besoin d’un site direct pour présenter son offre et générer des contacts.",
      },
      minimaliste: {
        description: "Site destiné à une activité dont l’identité, les contenus et le parcours sont déjà définis.",
        result: "Exemple : présentation d’activité, services, informations pratiques et contact.",
      },
    },
  },
  {
    id: "site-sur-mesure",
    group: "website",
    step: "1.2",
    name: "Personnaliser",
    title: "Site vitrine sur mesure",
    price: "À partir de 2 500 €*",
    description: "Pour construire une expérience propre à l’activité lorsque plusieurs publics, contenus ou parcours doivent être pris en compte.",
    details: ["Architecture et direction visuelle spécifiques", "Plusieurs publics ou parcours", "Interactions et intégrations propres à l’activité", "Tests, mise en ligne et repères de gestion"],
    voices: {
      accueillant: {
        description: "Pour créer une expérience qui s’adapte réellement à la personnalité du projet et aux sensibilités de ses visiteurs.",
        result: "Exemple : The Code of SP change ses couleurs, ses formes et ses textes selon l’univers choisi par le visiteur.",
      },
      affirme: {
        description: "Pour faire de l’identité et des parcours une démonstration visible du positionnement de l’activité.",
        result: "Exemple : The Code of SP déploie trois directions visuelles et éditoriales complètes dans une même architecture.",
      },
      minimaliste: {
        description: "Conception spécifique lorsque l’identité, les contenus ou les parcours doivent varier selon le visiteur.",
        result: "Exemple : The Code of SP adapte l’interface et le texte à trois univers distincts.",
      },
    },
  },
  {
    id: "application-plateforme",
    group: "product",
    step: "2.2",
    name: "Construire",
    title: "Application ou plateforme",
    price: "À partir de 4 500 €",
    description: "Pour transformer un besoin suffisamment défini en une solution fonctionnelle, testable et capable d’évoluer.",
    details: ["Parcours, interfaces et architecture", "Développement front-end et back-end", "Comptes, rôles, données ou administration selon le besoin", "Tests, déploiement et préparation des évolutions"],
    voices: {
      accueillant: {
        description: "Pour donner vie à une solution utile, construite autour des personnes qui l’utiliseront et prête à grandir avec le projet.",
        result: "L’exploration peut devenir sa première étape. Si le besoin est déjà clair, la conception peut commencer directement.",
      },
      affirme: {
        description: "Pour transformer une ambition structurée en produit fonctionnel, démontrable et prêt à rencontrer ses premiers utilisateurs.",
        result: "La feuille de route alimente directement la conception. Un projet déjà défini peut entrer sans détour dans cette phase.",
      },
      minimaliste: {
        description: "Conception et développement d’un produit à partir d’un périmètre suffisamment défini.",
        result: "Entrée possible après l’exploration ou directement si le besoin est déjà structuré.",
      },
    },
  },
];

export const methodOfferCoverage = [
  ["Faire mûrir", "Présence essentielle", "Site sur mesure", "Application / plateforme"],
  ["Faire mûrir", "Présence essentielle", "Site sur mesure", "Application / plateforme"],
  ["Faire mûrir", "Présence essentielle", "Site sur mesure", "Application / plateforme"],
  ["Présence essentielle", "Site sur mesure", "Application / plateforme"],
  ["Présence essentielle", "Site sur mesure", "Application / plateforme"],
  ["Présence essentielle", "Site sur mesure", "Application / plateforme"],
];

export const method = [
  ["Comprendre", "Ton activité, ton idée, ton public et ce qui rend le projet important."],
  ["Cadrer", "Le périmètre, les priorités et une première version réaliste."],
  ["Concevoir", "Les contenus, les parcours, les maquettes et l’identité de l’expérience."],
  ["Développer", "Une architecture claire et les fonctionnalités utiles, écrites sur mesure."],
  ["Tester", "Le responsive, l’accessibilité, les comportements et les cas d’erreur."],
  ["Mettre en ligne", "Une version de validation, tes derniers retours puis la mise en ligne définitive sur OVH."],
];

export const detailedMethod = [
  ["Comprendre", "Nous commençons par ton activité, ton idée, tes objectifs et les personnes auxquelles la solution doit servir. Je rassemble les informations utiles, reformule le besoin et identifie avec toi les contraintes qui peuvent influencer le projet.", "À l’issue de cette étape : une vision partagée du besoin et des objectifs à atteindre."],
  ["Cadrer", "Je transforme cette vision en un périmètre concret : parcours prioritaires, fonctionnalités indispensables, contenus attendus, contraintes techniques et ordre de réalisation. Les idées intéressantes mais non essentielles sont conservées pour une évolution future.", "À l’issue de cette étape : un périmètre réaliste, une feuille de route et des priorités claires."],
  ["Concevoir", "Je structure l’information, les écrans et les interactions avant le développement. Selon le projet, cette phase comprend l’arborescence, les parcours utilisateurs, les maquettes responsive et la direction visuelle.", "À l’issue de cette étape : une solution visualisable et validable avant sa mise en code."],
  ["Développer", "Je traduis les décisions validées en une solution sur mesure. J’organise le code pour qu’il reste lisible, maintenable et capable d’évoluer, tout en reliant les interfaces aux fonctionnalités nécessaires.", "À l’issue de cette étape : une première version fonctionnelle disponible dans un environnement de préproduction."],
  ["Tester", "Je vérifie les parcours, les formulaires, les différents formats d’écran et les principaux cas d’erreur. La recette te permet ensuite de parcourir la solution dans des conditions proches de son utilisation réelle et de centraliser tes retours.", "À l’issue de cette étape : une version corrigée et validée avant sa publication."],
  ["Mettre en ligne et transmettre", "Après ta validation, je déploie la solution, contrôle son fonctionnement et te transmets les repères nécessaires pour l’utiliser et la faire évoluer sereinement. Je peux ensuite intervenir ponctuellement pour la maintenance ou les évolutions, sans t’imposer un abonnement qui ne correspond pas à ton besoin.", "À l’issue de cette étape : une solution en ligne et les clés nécessaires pour la prendre en main."],
];

export const caseStudies = [
  {
    slug: "the-code-of-sp",
    liveUrl: SITE.domain,
    repositoryUrl: "https://github.com/TheCodeofSP/portfolio-thecodeofsp",
    title: "The Code of SP",
    category: "Identité numérique",
    hook: "Trois personnalités, une même expertise.",
    summary: "Concevoir un site capable d’adapter son ton et sa mise en scène à la sensibilité de chaque visiteur.",
    problem: "Présenter une activité de développement web sans réduire l’expérience à une liste de compétences techniques.",
    response: "Un parcours d’entrée inspiré d’une recherche Google permet de choisir un univers Accueillant, Affirmé ou Minimaliste. Le fond reste cohérent, tandis que le ton et la mise en scène s’adaptent.",
    result: "Une démonstration concrète de la capacité de The Code of SP à comprendre différents univers et à les traduire dans une expérience cohérente.",
    stack: ["React", "Vite", "Sass", "React Router"],
    status: "Projet personnel — en ligne",
    duration: "4 mois",
    role: "Cadrage, conception, direction visuelle et développement",
    hero: "/media/case-studies/the-code-of-sp/portfolio-05-choix-univers.webp",
    heroAlt: "Écran de choix entre les univers Accueillant, Affirmé et Minimaliste du portfolio The Code of SP",
    context: "The Code of SP devait présenter mes compétences et mes réalisations tout en donnant à ressentir ma manière de comprendre un univers, de structurer une intention et de la traduire dans une expérience numérique singulière.",
    challenge: "Faire du portfolio une démonstration de mon positionnement : écouter, cadrer, concevoir et coder une solution qui ne ressemble pas à un modèle générique.",
    decisions: [
      "Créer une entrée inspirée d’un moteur de recherche pour installer immédiatement une expérience interactive.",
      "Proposer trois univers complets, et pas seulement trois palettes de couleurs.",
      "Adapter le vocabulaire, les formes, les animations et la mise en scène à chaque sensibilité.",
      "Conserver la même structure et les mêmes offres afin que la personnalité visuelle ne masque jamais l’information.",
      "Faire du formulaire de découverte un premier outil de cadrage, avec une voie de contact libre en parallèle.",
    ],
    highlights: [
      ["3", "univers visuels et éditoriaux"],
      ["4 mois", "de conception, développement et mise en ligne"],
      ["Responsive", "effets adaptés au tactile et aux petits écrans"],
    ],
    mediaGroups: [
      { title: "Une entrée qui installe immédiatement l’expérience", intro: "La recherche guide le visiteur vers l’univers qui correspond le mieux à sa sensibilité.", layout: "before-after", items: [
        ["portfolio-04-introduction.webp", "Introduction du portfolio inspirée d’une recherche", "Formuler sa recherche"],
        ["portfolio-05-choix-univers.webp", "Choix entre les trois univers du portfolio", "Choisir son univers"],
      ] },
      { title: "Une même expertise, trois expressions", intro: "Chaque univers garde le même fond, mais adopte sa propre voix visuelle.", layout: "three", items: [
        ["portfolio-24-comparaison-accueillant.webp", "Page d’accueil dans l’univers Accueillant", "Accueillant — doux et organique"],
        ["portfolio-25-comparaison-affirme.webp", "Page d’accueil dans l’univers Affirmé", "Affirmé — énergique et direct"],
        ["portfolio-26-comparaison-minimaliste.webp", "Page d’accueil dans l’univers Minimaliste", "Minimaliste — précis et épuré"],
      ] },
      { title: "Le parcours jusque dans la prise de contact", intro: "Le système accompagne aussi les visiteurs lorsqu’ils souhaitent préciser leur besoin.", layout: "three", items: [
        ["portfolio-27-formulaire-niveau-01.webp", "Premier niveau du formulaire de découverte", "Découvrir l’activité"],
        ["portfolio-28-formulaire-niveau-02.webp", "Deuxième niveau du formulaire de découverte", "Comprendre l’idée"],
        ["portfolio-29-formulaire-je-ne-sais-pas.webp", "Message affiché lorsqu’un budget reste à définir", "Rassurer sans forcer une réponse"],
      ] },
    ],
    videos: [
      ["portfolio-video-01-introduction.mp4", "De la recherche au choix des trois univers"],
      ["portfolio-video-02-changement-univers.mp4", "Passage d’un univers à l’autre"],
      ["portfolio-video-03-mobile.mp4", "Adaptation de l’expérience sur mobile"],
    ],
    closing: "Ce projet ne se contente pas de dire que je sais m’adapter : il le fait expérimenter dès les premières secondes.",
    cta: "Construire une identité numérique qui te ressemble",
  },
  {
    slug: "manon-pontasse",
    liveUrl: "https://www.manonpontasse-educatriceliberale.fr/",
    repositoryUrl: "https://github.com/TheCodeofSP/manon-pontasse-educatrice-liberale",
    title: "Manon Pontasse",
    category: "Projet client",
    hook: "Rendre une activité sensible claire, accessible et rassurante.",
    summary: "Un site vitrine pensé pour guider les familles, les aidants et les partenaires vers les bonnes informations.",
    problem: "Expliquer une activité d’éducatrice spécialisée indépendante à plusieurs publics, avec des attentes différentes.",
    response: "Une architecture éditoriale claire, des contenus adaptés aux profils visiteurs et un parcours de contact simple.",
    result: "Une présence professionnelle cohérente avec l’activité, plus lisible et plus rassurante pour chaque public.",
    stack: ["React", "JavaScript", "Sass", "Responsive"],
    status: "Site en ligne",
    role: "Cadrage, conception, numérisation du logo et développement",
    hero: "/media/case-studies/manon-pontasse/manon-01-accueil-desktop.webp",
    heroAlt: "Page d’accueil du site de Manon Pontasse, éducatrice spécialisée indépendante",
    context: "Manon s’adresse à des personnes accompagnées, à leurs proches et à des partenaires sociaux. Ces visiteurs n’ont ni les mêmes questions, ni le même niveau de connaissance, ni la même relation à l’accompagnement.",
    challenge: "Créer un site rassurant et structuré qui adapte les premiers repères au profil du visiteur, tout en gardant une navigation simple et une identité douce.",
    decisions: [
      "Installer dès l’accueil un choix entre trois profils de visiteurs.",
      "Adapter l’introduction, la page Mon approche et les sujets du formulaire au profil sélectionné.",
      "Présenter les informations utiles sans alourdir le parcours ni le contenu.",
      "Conserver un contact volontairement simple grâce à un message prérempli dans la messagerie du visiteur.",
      "Numériser le logo existant de Manon afin de le rendre utilisable sur ses différents supports.",
    ],
    highlights: [
      ["3", "profils de visiteurs pris en compte"],
      ["Identité", "un logo existant rendu exploitable en numérique"],
      ["Sur mesure", "des mots adaptés à chaque interlocuteur"],
    ],
    mediaGroups: [
      { title: "Commencer par reconnaître la personne qui visite", intro: "Le même emplacement accueille trois introductions différentes pour créer un premier repère juste.", layout: "three", items: [
        ["manon-04-profil-accompagne.webp", "Introduction destinée à une personne accompagnée", "La personne accompagnée"],
        ["manon-05-profil-accompagnant.webp", "Introduction destinée à un proche accompagnant", "Le proche ou l’accompagnant"],
        ["manon-06-profil-partenaire.webp", "Introduction destinée à un partenaire social", "Le partenaire social"],
      ] },
      { title: "Approfondir sans perdre la douceur", intro: "La page Mon approche poursuit cette adaptation avec des repères plus détaillés.", layout: "three", items: [
        ["manon-07-approche-accompagne1.webp", "Page Mon approche pour une personne accompagnée", "Une approche accessible"],
        ["manon-08-approche-accompagnant1.webp", "Page Mon approche pour un accompagnant", "Une relation de confiance"],
        ["manon-09-approche-partenaire1.webp", "Page Mon approche pour un partenaire", "Une logique de coordination"],
      ] },
      { title: "Informer et guider vers le bon échange", layout: "three", items: [
        ["manon-10-accompagnements.webp", "Présentation des accompagnements proposés par Manon", "Les accompagnements"],
        ["manon-12-informations.webp", "Page pédagogique sur la déficience intellectuelle", "Les informations pédagogiques"],
        ["manon-15-contact-sujets1.webp", "Sujets du formulaire adaptés au profil", "Un contact contextualisé"],
      ] },
      { title: "D’un logo physique à un actif numérique", intro: "Le logo existant a été recréé numériquement afin de pouvoir être utilisé proprement sur les différents supports de Manon.", layout: "before-after", items: [
        ["manon-16-logo-original.webp", "Logo original fourni par Manon avant sa numérisation", "Le logo transmis"],
        ["manon-22-logo-final.svg", "Logo final numérisé de Manon Pontasse", "La version numérique finale"],
      ] },
    ],
    videos: [
      ["manon-video-01-changement-profil.mp4", "Adaptation de l’accueil selon le profil"],
      ["manon-video-02-parcours-contact.mp4", "Du choix du profil aux motifs de contact"],
    ],
    testimonial: {
      author: "Manon Pontasse",
      role: "Éducatrice spécialisée indépendante",
      quote: [
        "Merci à Sandrine pour la création de mon site ! J’ai vraiment apprécié son écoute et sa disponibilité tout au long du projet. Elle prend le temps d’échanger, de comprendre les besoins et de modifier les choses jusqu’à ce que ce soit vraiment juste.",
        "Elle est aussi force de proposition, avec toujours de bonnes idées et un vrai regard professionnel. On sent qu’elle s’investit pleinement pour que le résultat soit cohérent et de qualité.",
        "Et surtout, elle continue à suivre les évolutions et à faire de la veille même après la création du site, ce qui est vraiment appréciable.",
        "Une super expérience, je recommande Sandrine les yeux fermés !",
      ],
    },
    closing: "Le résultat est un site qui ne demande pas aux visiteurs de s’adapter au vocabulaire professionnel : il fait le premier pas vers eux.",
    cta: "Créer un site qui parle vraiment à tes publics",
  },
  {
    slug: "the-quiz-of-sp",
    liveUrl: "https://thequizofsp.vercel.app/",
    repositoryUrl: "https://github.com/TheCodeofSP/thequizofsp-v2",
    title: "The Quiz of SP",
    category: "Produit personnel",
    hook: "Transformer la découverte d’une personnalité en expérience ludique.",
    summary: "Une application de quiz interactive, conçue du parcours utilisateur jusqu’à l’enregistrement des scores.",
    problem: "Partager des centres d’intérêt d’une façon plus engageante qu’une simple page de présentation.",
    response: "Une expérience de quiz avec logique de progression, calcul des résultats et architecture full-stack.",
    result: "Un produit complet qui démontre la capacité à concevoir une idée, organiser ses données et développer son fonctionnement.",
    stack: ["React", "Node.js", "Express", "MongoDB"],
    status: "Projet interne — en ligne",
    role: "Concept, game design, direction visuelle et développement full-stack",
    audience: "Une dizaine de premières parties, avant diffusion élargie",
    hero: "/media/case-studies/the-quiz-of-sp/quiz-03-accueil.png",
    heroAlt: "Écran d’accueil de The Quiz of SP dans son univers arcade",
    context: "Le projet répond à une question personnelle : comment faire découvrir mes goûts et mes centres d’intérêt de manière plus vivante qu’avec une page À propos ? Les questions portent directement sur mon univers, même lorsqu’elles ressemblent au premier regard à de la culture générale.",
    challenge: "Transformer cette découverte en un jeu suffisamment clair pour être compris immédiatement, mais assez rythmé pour donner envie d’aller jusqu’au boss final.",
    decisions: [
      "Abandonner une première piste orange et verte, trop générique pour servir l’objectif du projet.",
      "Construire une direction arcade complète avec sons, retours visuels et vocabulaire de jeu.",
      "Organiser 170 questions en trois niveaux de difficulté et en tirer une sélection aléatoire à chaque partie.",
      "Créer une mécanique Quitte ou double qui laisse le joueur sécuriser son score ou tenter la finale.",
      "Faire recalculer les scores par l’API avant leur enregistrement dans le classement.",
    ],
    highlights: [
      ["170", "questions réparties sur trois niveaux"],
      ["50 pts", "score maximal après le quitte ou double"],
      ["Full-stack", "jeu, API et classement en ligne"],
    ],
    mediaGroups: [
      { title: "Une progression immédiatement lisible", layout: "three", items: [
        ["quiz-05-niveau-01.png", "Question du premier niveau de The Quiz of SP", "Niveau 1 — cinq questions"],
        ["quiz-09-niveau-02-timer.png", "Question chronométrée du deuxième niveau", "Niveau 2 — dix secondes par question"],
        ["quiz-11-final-boss.png", "Question du boss final", "Niveau 3 — la question finale"],
      ] },
      { title: "Des décisions qui donnent du rythme", layout: "three", items: [
        ["quiz-06-bonne-reponse.png", "Retour visuel après une bonne réponse", "Gagner des points"],
        ["quiz-10-quitte-ou-double.png", "Choix entre sécuriser son score ou tenter le quitte ou double", "Prendre le risque"],
        ["quiz-12-resultat-gagne.png", "Écran de résultat après une victoire", "Doubler son score"],
      ] },
      { title: "Une expérience complète, jusque dans le classement", layout: "three", items: [
        ["quiz-14-classement-anonymise.png", "Classement en ligne avec des pseudonymes", "Le classement en ligne"],
        ["quiz-13-resultat-perdu.png", "Résultat après une mauvaise réponse finale", "Le risque fait partie du jeu"],
        ["quiz-15-mobile.png", "Version mobile de The Quiz of SP", "Une partie jouable sur mobile"],
      ] },
    ],
    videos: [
      ["quiz-video-01-partie.mp4", "Le déroulement d’une partie"],
      ["quiz-video-02-quitte-ou-double.mp4", "La mécanique Quitte ou double"],
    ],
    evolution: "Les captures de la première direction visuelle, la documentation Swagger et la donnée MongoDB ne sont pas nécessaires pour comprendre l’expérience. Elles restent donc hors de cette version de l’étude.",
    closing: "Ce projet montre qu’une idée légère peut être traitée comme un véritable produit : avec une intention, des règles, une architecture et des choix proportionnés à son usage.",
    cta: "Transformer une idée originale en expérience interactive",
  },
  {
    slug: "stratusse",
    liveUrl: "https://www.stratusse.fr/",
    repositoryUrl: "https://github.com/TheCodeofSP/stratusse-code",
    title: "Stratusse",
    category: "Produit personnel",
    hook: "Donner une place aux pensées qui ont besoin d’exister.",
    summary: "Une plateforme communautaire d’écriture et de lecture conçue avec des rôles, une modération et une attention particulière portée aux auteurs.",
    problem: "Permettre le partage de pensées personnelles sans ignorer ce qui peut arriver lorsqu’elles reçoivent une réponse blessante ou inadaptée.",
    response: "Une application full-stack qui relie publication, lecture, profils, réactions et administration dans un cadre guidé par une charte et des outils de modération.",
    result: "Un produit complet qui démontre une capacité à relier vision, expérience utilisateur, sécurité et décisions d’administration.",
    stack: ["React", "Vite", "Sass", "Express", "MongoDB", "Zod", "Resend"],
    status: "Lancement préparé pour fin 2026",
    role: "Projet personnel — stratégie produit, conception, développement full-stack et administration",
    value: "Valeur estimée : projet de cette ampleur à partir de 35 000 €",
    hero: "/media/case-studies/stratusse/stratusse-01-accueil-desktop.png",
    heroAlt: "Page d’accueil de Stratusse",
    context: "Stratusse est né de l’envie de créer un lieu où déposer une pensée, découvrir celles des autres et recommander des lectures. Pour concevoir ce projet personnel avec exigence, je me suis placée dans la posture de ma propre cliente : objectifs, parcours, priorités, recette et lancement.",
    challenge: "Préserver la liberté d’expression tout en donnant aux auteurs et à l’administration des moyens concrets de prévenir et traiter les interactions qui peuvent blesser.",
    decisions: [
      "Distinguer les rôles membre, Voix et administrateur pour adapter les droits à chaque usage.",
      "Soumettre les demandes pour devenir une Voix à une validation humaine.",
      "Centraliser la validation, la suppression et la modération des contenus dans un tableau de bord dédié.",
      "Sécuriser les formulaires et les sessions avec validation des données, limitation des tentatives et cookies sécurisés.",
      "Conditionner la mesure d’audience au consentement et préparer un lancement progressif.",
    ],
    highlights: [
      ["3", "rôles et niveaux de permission"],
      ["Full-stack", "publication, comptes et administration"],
      ["35 000 €+", "valeur estimée d’un projet de cette ampleur"],
    ],
    mediaGroups: [
      { title: "Lire, réagir et découvrir", layout: "three", items: [
        ["stratusse-03-notes-liste.png", "Liste des Notes publiées sur Stratusse", "Découvrir les Notes"],
        ["stratusse-04-note-detail.png", "Détail d’une Note sur Stratusse", "Entrer dans une réflexion"],
        ["stratusse-06-bibliotheque.png", "Bibliothèque de recommandations de lecture", "Partager des lectures"],
      ] },
      { title: "Passer de la lecture à l’écriture", layout: "three", items: [
        ["stratusse-09-inscription.png", "Formulaire d’inscription sécurisé de Stratusse", "Créer un compte"],
        ["stratusse-13-demande-voix.png", "Demande pour devenir une Voix", "Demander à publier"],
        ["stratusse-11-editeur-note.png", "Éditeur de nouvelle Note", "Écrire une Note"],
      ] },
      { title: "Administrer sans perdre la dimension humaine", intro: "Les captures utilisent uniquement les données fictives préparées pour la démonstration.", layout: "three", items: [
        ["stratusse-14-dashboard-admin.png", "Tableau de bord administrateur de Stratusse", "Suivre l’activité"],
        ["stratusse-16-moderation-commentaire.png", "Outil de modération d’un commentaire", "Protéger les auteurs"],
        ["stratusse-18-validation-voix.png", "Validation d’une demande pour devenir une Voix", "Valider les nouveaux profils"],
      ] },
      { title: "Une expérience pensée pour plusieurs écrans", layout: "before-after", items: [
        ["stratusse-01-accueil-desktop.png", "Accueil de Stratusse sur ordinateur", "Vue ordinateur"],
        ["stratusse-02-accueil-mobile.png", "Accueil de Stratusse sur mobile", "Vue mobile"],
      ] },
    ],
    videos: [
      ["stratusse-video-01-experience-publique.mp4", "De l’accueil à la lecture d’une Note"],
      ["stratusse-video-02-publication1.mp4", "La publication d’une Note"],
      ["stratusse-video-03-moderation.mp4", "Le parcours de modération"],
    ],
    evolution: "La première version réunit la publication, la lecture, les commentaires, les rôles et la modération. Elle servira à présenter le projet à ses futurs collaborateurs et à préparer avec eux la suite de son développement. Une deuxième version sera ensuite destinée au public.",
    closing: "Stratusse matérialise ma capacité à porter un produit de bout en bout, y compris dans les décisions moins visibles : permissions, sécurité, modération, données et préparation du lancement.",
    cta: "Cadrer et développer une plateforme ambitieuse",
  },
  {
    slug: "projet-en-cours",
    liveUrl: null,
    title: "Un projet d’envergure se construit",
    category: "Plateforme en cours de développement",
    hook: "Transformer une demande initiale en une vision produit plus vaste.",
    summary: "Un projet confidentiel actuellement structuré, développé et validé bloc après bloc.",
    problem: "Une demande centrée sur une première fonctionnalité a révélé un besoin plus large, impliquant plusieurs publics, espaces et parcours complémentaires.",
    response: "Un travail de cadrage et une feuille de route découpée en blocs permettent de construire progressivement la plateforme, tout en laissant chaque décision être validée avant la suivante.",
    result: "Une architecture full-stack déjà conséquente, encore en développement et présentée sans dévoiler son identité ni ses fonctionnalités.",
    stack: ["React", "Vite", "Sass", "Express", "MongoDB", "Tests automatisés"],
    status: "Projet en cours — interface et contenus non dévoilés",
    role: "Cadrage, conception produit, pilotage et développement full-stack",
    value: "Valeur estimée à ce stade : 45 000 à 60 000 €",
    hero: "/media/case-studies/projet-mystere/melanie-01-projet-mystere.webp",
    heroAlt: "Composition énigmatique présentant une plateforme en cours de développement",
    context: "Ce projet est volontairement présenté sans nom, sans captures identifiables et sans description détaillée de ses modules. Cette confidentialité permet néanmoins de montrer la nature du travail engagé : comprendre un besoin qui évolue, élargir le périmètre avec méthode et construire une solution complexe sans perdre la direction initiale.",
    challenge: "Faire évoluer la vision au fil des échanges, tout en distinguant ce qui est développé, ce qui reste à valider et ce qui appartient à une version future.",
    decisions: [
      "Reprendre le cadrage avant de poursuivre le développement.",
      "Transformer les besoins en blocs de travail lisibles et priorisés.",
      "Présenter régulièrement des versions intermédiaires pour recueillir des décisions concrètes.",
      "Préparer une architecture capable d’accueillir plusieurs types d’utilisateurs et de parcours.",
      "Conserver l’étude complète, les interfaces et les résultats pour une publication après validation finale.",
    ],
    highlights: [
      ["Multi-rôles", "des parcours adaptés à plusieurs publics"],
      ["Bloc par bloc", "une validation progressive"],
      ["45–60 k€", "valeur estimée de la plateforme complète"],
    ],
    mediaGroups: [],
    videos: [],
    evolution: "À la fin du projet, cette étude pourra être enrichie avec l’avant/après, les parcours, les choix d’architecture, les modules validés, le témoignage et les résultats observés.",
    closing: "Cette présentation partielle montre déjà l’essentiel : ma capacité à lire au-delà d’une demande initiale et à transformer une idée en produit structuré, pilotable et évolutif.",
    cta: "Transformer une idée complexe en feuille de route",
  },
];
import { SITE } from "../config/site.config.js";
