import { normalizeTheme } from "../config/themes.config.js";

export const themedPageCopy = {
  accueillant: {
    home: {
      pathsKicker: "Deux façons de commencer",
      pathsTitle: "Partons de là où tu en es, avec ce qui est déjà clair et ce qui l’est moins.",
      paths: [
        ["« Je sais ce que je veux. »", "Tu as une demande précise. Nous prenons le temps de l’ajuster à ton activité, à ta personnalité et aux personnes que tu veux toucher."],
        ["« Mon idée demande encore à mûrir. »", "Tu n’as pas besoin d’avoir toutes les réponses. Nous pouvons mettre des mots sur ton idée et dessiner ensemble un premier chemin réaliste."],
      ],
      methodKicker: "Construire ensemble",
      methodTitle: "Une méthode qui donne des repères sans effacer ton intuition.",
      methodLink: "Découvrir les services et la méthode →",
      projectsKicker: "Des histoires devenues projets",
      projectsTitle: "Chaque réalisation commence par une personne, un besoin et une intention singulière.",
      projectLink: "Entrer dans l’histoire du projet →",
      storyKicker: "Sandrine, derrière The Code of SP",
      storyTitle: "De la rigueur, de l’écoute et une présence humaine à chaque étape.",
      story: [
        "Tu gardes une interlocutrice unique de la première réflexion à la mise en ligne. Je prends le temps de comprendre ce qui compte pour toi, puis je rends chaque étape et chaque décision lisibles.",
        "Ma manière de travailler réunit écoute, organisation et développement sur mesure. Elle permet de construire une solution fidèle à ton activité, sans te perdre dans la technique.",
        "Les outils peuvent accélérer certaines tâches, mais l’analyse du besoin, les choix et la responsabilité du résultat restent profondément humains.",
      ],
      storyLink: "Faire connaissance sur LinkedIn →",
      ctaKicker: "On peut commencer simplement",
      ctaTitle: "Ton projet peut encore être flou. Il mérite déjà d’être écouté.",
      ctaText: "Raconte-moi son point de départ. Je prendrai le temps de te répondre personnellement sous une semaine.",
      ctaButton: "Me parler de ton idée",
    },
    services: {
      kicker: "Services & méthode",
      title: "De ton idée à sa mise en ligne, avançons étape par étape.",
      intro: "Un site essentiel et une plateforme ambitieuse ne demandent pas le même travail. Nous définissons une solution adaptée à ta réalité, à tes moyens et à ton rythme, puis je la construis jusqu’à sa mise en ligne.",
      commitmentsKicker: "De l’idée à une solution qui vit vraiment",
      commitmentsTitle: "Une réalisation pensée, construite et mise entre tes mains.",
      commitments: [
        ["Conception", "Nous mettons des mots sur le besoin, choisissons les priorités et imaginons une solution fidèle à ton activité et aux personnes que tu veux toucher."],
        ["Développement", "Je transforme les choix validés en une solution responsive, fiable et conçue avec soin pour ton projet."],
        ["Mise en ligne", "Je prépare le lancement, vérifie le fonctionnement final et te transmets des repères simples pour faire vivre ta solution."],
      ],
      offersKicker: "Plusieurs portes d’entrée",
      offersTitle: "Des services adaptés au point de départ et à l’ambition de ton projet.",
      productKicker: "Faire grandir une idée",
      productTitle: "De la première intuition à une solution que l’on peut utiliser.",
      productIntro: "L’idée peut encore avoir besoin de mots et de repères, ou être déjà assez mûre pour entrer en conception. Ces deux services se répondent sans t’obliger à recommencer le travail réalisé.",
      productBridge: "La feuille de route devient la base de la conception. Si ton besoin est déjà clair, nous pouvons commencer directement par l’application ou la plateforme.",
      productPriceNote: "* Le package Exploration et feuille de route rassemble le travail nécessaire pour faire mûrir l’idée et organiser sa suite. Si ton budget demande d’avancer progressivement, certaines interventions peuvent être commandées séparément, comme une préparation technique à partir de 300 €. Je peux aussi rester impliquée comme partenaire technique pendant la recherche de financement, dans le cadre d’une mission distincte.",
      websiteKicker: "Présenter une activité",
      websiteTitle: "Une présence essentielle ou une expérience entièrement personnalisée.",
      websiteIntro: "La différence dépend surtout de ce que le site doit traduire. Une activité déjà définie demande moins de conception qu’une expérience dont les textes, les parcours et l’univers changent selon le visiteur.",
      websitePriceNote: "* Le tarif dépend du périmètre, des contenus et des fonctionnalités du site. Le devis peut répartir le règlement entre plusieurs étapes : la première facture ouvre la conception, la suivante le développement, puis le solde la mise en ligne.",
      methodKicker: "Des repères à chaque étape",
      methodTitle: "Tu restes au cœur des décisions. Je veille à les transformer en une solution concrète.",
      methodOffersLabel: "Les offres qui comprennent cette étape",
      networkKicker: "Les bonnes compétences au bon moment",
      networkTitle: "Ton projet peut aussi avoir besoin d’un regard spécialisé.",
      network: ["Si ton projet le demande, je peux faire intervenir une tierce personne après t’en avoir parlé : direction graphique, sécurité, marketing, SEO ou toute autre expertise utile. Sa prestation peut rejoindre mon devis pour te laisser une seule interlocutrice, ou être contractualisée directement avec elle.", "Après la mise en ligne, je reste disponible pour les évolutions et la maintenance dont tu as réellement besoin, sans t’imposer un abonnement inutile."],
      ctaTitle: "De quels services ton projet a-t-il besoin aujourd’hui ?",
      ctaText: "Le formulaire de découverte nous aidera à poser un premier repère, sans t’obliger à avoir déjà tout défini.",
      ctaButton: "Partager ton point de départ",
    },
    projects: {
      kicker: "Réalisations",
      title: "Derrière chaque interface, il y a une histoire à comprendre.",
      intro: "Ces projets sont nés de réalités très différentes. Découvre comment leur conception, leur développement et leur mise en ligne leur ont donné une forme juste.",
      studyButton: "Découvrir son histoire",
      liveButton: "Visiter le projet",
    },
    caseUi: {
      openProject: "Découvrir le projet",
      openStudy: "Entrer dans son histoire ↓",
      status: "Où en est le projet",
      role: "Mon rôle",
      duration: "Temps consacré",
      audience: "Premiers retours",
      value: "Valeur du travail",
      contextKicker: "Le point de départ",
      contextTitle: "Écouter l’histoire avant d’imaginer la solution.",
      challengeKicker: "Ce qu’il fallait résoudre",
      challengeTitle: "Trouver une réponse fidèle au besoin.",
      decisionsKicker: "Les choix qui ont guidé le projet",
      decisionsTitle: "Chaque décision prend soin de l’intention de départ.",
      highlights: "Quelques repères pour comprendre le projet",
      interface: "Le projet prend forme",
      motion: "Le parcours en mouvement",
      motionTitle: "Voir l’expérience se dérouler.",
      testimonialKicker: "Les mots de Manon",
      testimonialTitle: "Une collaboration vécue avec confiance.",
      result: "Ce que cette réalisation raconte",
      next: "La suite du chemin",
      stack: "Les outils qui soutiennent le projet",
      repository: "Découvrir le code sur GitHub ↗",
      ctaKicker: "Et ton projet ?",
      ctaText: "Tu peux venir avec une question, une intuition ou un besoin déjà précis. Nous partirons de ta réalité.",
      ctaButton: "Me raconter ton idée",
      back: "← Revenir aux réalisations",
    },
    contact: {
      kicker: "Me contacter",
      title: "Parlons de ce dont tu as besoin, simplement.",
      intro: "Tu peux venir avec une question ou me raconter un projet déjà mûr. Choisis le point de départ dans lequel tu te sens le plus à l’aise.",
      inquiryKicker: "Une question, sans engagement",
      inquiryTitle: "Tu veux d’abord échanger librement ?",
      inquiryText: "Écris-moi sans avoir à formaliser un projet ni à remplir le questionnaire complet.",
      inquiryButton: "M’envoyer un message",
      projectKicker: "Une idée à faire grandir",
      projectTitle: "Tu souhaites me confier le point de départ d’un projet ?",
      projectText: "Le formulaire m’aide à comprendre ton activité et à préparer une première réponse attentive.",
      projectButton: "Me raconter mon projet",
      freeKicker: "Contact libre",
      freeTitle: "Je t’écoute.",
      freeText: "Une question sur mes services, un besoin d’information ou simplement l’envie de faire connaissance.",
      formKicker: "Découvrir ton projet",
      formTitle: "Commençons par ce qui compte pour toi.",
      formText: "Prévois environ 8 minutes. Tes réponses me permettront de comprendre ta réalité avant de te proposer une suite.",
    },
  },
  affirme: {
    home: {
      pathsKicker: "Deux points de départ. Une décision : avancer.",
      pathsTitle: "Besoin précis ou idée brute : transformons-le en projet solide.",
      paths: [["« Mon objectif est clair. »", "Parfait. Nous challengeons la demande, fixons les priorités et construisons une présence capable de prendre position."], ["« J’ai une idée à structurer. »", "Nous sortons l’idée du flou, testons sa cohérence et définissons une première version que tu peux défendre et faire évoluer."]],
      methodKicker: "Passer à l’action",
      methodTitle: "Six étapes pour décider vite, construire juste et garder le cap.",
      methodLink: "Voir les services et la méthode →",
      projectsKicker: "La preuve par les projets",
      projectsTitle: "Des ambitions concrètes. Des décisions fortes. Des produits qui prennent vie.",
      projectLink: "Voir les décisions prises →",
      storyKicker: "Sandrine · The Code of SP",
      storyTitle: "Une développeuse qui pilote autant qu’elle code.",
      story: ["Je pilote chaque réalisation de l’analyse du besoin jusqu’à sa mise en ligne, avec un objectif clair : transformer une ambition en solution réellement utilisable.", "Ma rigueur de pilotage s’appuie sur dix ans d’expérience dans des environnements opérationnels exigeants, aujourd’hui mise au service de la conception et du développement web.", "L’IA accélère certaines tâches. La stratégie, les arbitrages et la responsabilité du résultat restent humains."],
      storyLink: "Voir mon parcours sur LinkedIn →",
      ctaKicker: "Prochaine étape",
      ctaTitle: "Une idée ne devient un projet que lorsqu’on décide de la structurer.",
      ctaText: "Expose-moi le besoin. Je l’analyse et je reviens vers toi sous une semaine avec une prochaine étape claire.",
      ctaButton: "Lancer la réflexion",
    },
    services: {
      kicker: "Services & méthode",
      title: "De la conception au lancement. Une réalisation maîtrisée de bout en bout.",
      intro: "Le périmètre doit servir l’objectif, pas gonfler le projet. Nous calibrons l’effort, les priorités et le niveau d’ambition avant d’engager le développement.",
      commitmentsKicker: "Une trajectoire complète",
      commitmentsTitle: "Concevoir. Développer. Mettre en ligne.",
      commitments: [
        ["Conception", "J’analyse le besoin, challenge les priorités et transforme l’ambition en une solution cohérente, défendable et prête à être exécutée."],
        ["Développement", "Je traduis les décisions en interfaces et fonctionnalités robustes, responsive et capables d’évoluer."],
        ["Mise en ligne", "Je pilote la recette, le déploiement et la transmission des clés nécessaires pour prendre le contrôle de la solution."],
      ],
      offersKicker: "Quatre formats pour avancer",
      offersTitle: "Quatre formats pour transformer ton objectif en résultat.",
      productKicker: "Idée et produit",
      productTitle: "Challenge l’idée. Défends le projet. Construis la solution.",
      productIntro: "Une idée encore brute commence par l’exploration. Un projet déjà solide peut entrer directement en conception. Dans les deux cas, chaque décision prépare l’exécution.",
      productBridge: "Aucune reprise inutile : la feuille de route alimente la conception. Si le périmètre est déjà maîtrisé, le développement peut commencer directement.",
      productPriceNote: "* Le package Exploration et feuille de route structure l’idée et prépare son exécution. Un budget serré peut avancer intervention par intervention, avec une préparation technique à partir de 300 €. Une mission distincte de partenaire technique peut ensuite couvrir la recherche de financement et les échanges avec les investisseurs.",
      websiteKicker: "Présence numérique",
      websiteTitle: "Le site essentiel présente. Le sur-mesure démontre le positionnement.",
      websiteIntro: "Le premier organise des contenus déjà prêts. Le second construit une expérience spécifique lorsque l’identité, les publics ou les parcours deviennent une partie centrale du projet.",
      websitePriceNote: "* Le prix final dépend du périmètre, des contenus et des fonctionnalités. Le budget peut être réparti par phases : conception, développement, puis mise en ligne. Chaque règlement débloque une étape identifiée dans le devis.",
      methodKicker: "Un pilotage sans zone grise",
      methodTitle: "Tu arbitres. Je transforme chaque décision en action puis en solution.",
      methodOffersLabel: "Inclus dans",
      networkKicker: "Expertise ciblée",
      networkTitle: "Quand le projet exige une compétence complémentaire, j’active la bonne expertise.",
      network: ["Après validation, une tierce personne peut rejoindre le projet pour répondre à un besoin précis : direction artistique, sécurité, marketing, SEO ou autre domaine spécialisé. Sa mission est intégrée à mon devis pour centraliser le pilotage, ou contractualisée directement selon l’organisation la plus efficace.", "Maintenance et évolutions sont déclenchées quand elles créent de la valeur. Aucun abonnement imposé."],
      ctaTitle: "Quel résultat veux-tu obtenir ?",
      ctaText: "Présente le besoin. Le questionnaire me permettra d’identifier rapidement le bon niveau d’intervention.",
      ctaButton: "Présenter le défi",
    },
    projects: {
      kicker: "Réalisations",
      title: "Des intentions traduites en décisions, puis en produits.",
      intro: "Chaque étude expose le problème, les arbitrages et le résultat. Pas seulement l’interface finale.",
      studyButton: "Analyser le projet",
      liveButton: "Voir le produit",
    },
    caseUi: {
      openProject: "Voir le produit",
      openStudy: "Analyser le projet ↓",
      status: "Statut",
      role: "Mon rôle",
      duration: "Durée",
      audience: "Premiers usages",
      value: "Valeur estimée",
      contextKicker: "Point de départ",
      contextTitle: "Le contexte qui impose la stratégie.",
      challengeKicker: "Le défi",
      challengeTitle: "Le problème à résoudre, sans détour.",
      decisionsKicker: "Arbitrages",
      decisionsTitle: "Des décisions assumées au service de l’objectif.",
      highlights: "Les chiffres clés",
      interface: "Exécution",
      motion: "Démonstration",
      motionTitle: "Le produit en action.",
      testimonialKicker: "Retour client",
      testimonialTitle: "Écoute, disponibilité et exigence jusqu’au résultat.",
      result: "Impact du projet",
      next: "Prochaine évolution",
      stack: "Stack technique",
      repository: "Voir le dépôt GitHub ↗",
      ctaKicker: "Ton prochain projet",
      ctaText: "Apporte le besoin, l’ambition ou le problème. Nous définirons la stratégie pour le transformer en solution.",
      ctaButton: "Passer à l’action",
      back: "← Retour aux réalisations",
    },
    contact: {
      kicker: "Contact",
      title: "Une question ou un projet ? Passe à l’étape suivante.",
      intro: "Choisis le format adapté : un message direct pour obtenir une réponse, ou un questionnaire pour poser les bases d’un projet.",
      inquiryKicker: "Question directe",
      inquiryTitle: "Besoin d’une information précise ?",
      inquiryText: "Va droit au but. Aucun cadrage préalable n’est nécessaire pour m’écrire.",
      inquiryButton: "Envoyer la question",
      projectKicker: "Projet à challenger",
      projectTitle: "Prête à transformer ton idée en plan d’action ?",
      projectText: "Le questionnaire rassemble les données utiles pour analyser le besoin et préparer un échange productif.",
      projectButton: "Présenter le projet",
      freeKicker: "Message direct",
      freeTitle: "Pose ta question.",
      freeText: "Services, faisabilité, collaboration : décris ce que tu veux savoir.",
      formKicker: "Cadrage initial",
      formTitle: "Donne-moi les éléments pour analyser ton idée.",
      formText: "Huit minutes suffisent pour exposer l’objectif, le public, le périmètre et les contraintes.",
    },
  },
  minimaliste: {
    home: {
      pathsKicker: "Deux situations",
      pathsTitle: "Un besoin défini ou une idée à cadrer.",
      paths: [["Besoin défini", "Le périmètre est précisé puis traduit en site professionnel, cohérent avec l’activité et ses utilisateurs."], ["Idée à cadrer", "Les objectifs, usages et priorités sont organisés avant de définir une première version réaliste."]],
      methodKicker: "Méthode",
      methodTitle: "Comprendre, décider, concevoir et livrer.",
      methodLink: "Consulter les services et la méthode →",
      projectsKicker: "Réalisations",
      projectsTitle: "Cinq projets. Cinq réponses à des besoins distincts.",
      projectLink: "Consulter l’étude →",
      storyKicker: "À propos",
      storyTitle: "Une double culture : organisation et développement web.",
      story: ["Un seul point de contact pour concevoir, développer et mettre en ligne la solution.", "Une méthode issue de dix années d’expérience en organisation et pilotage, associée à une expertise en développement web sur mesure.", "Les outils assistent l’exécution. L’analyse, les décisions et la responsabilité restent humaines."],
      storyLink: "Parcours LinkedIn →",
      ctaKicker: "Contact",
      ctaTitle: "Définissons le point de départ.",
      ctaText: "Décris le besoin, même brièvement. Une réponse personnelle te sera adressée sous une semaine.",
      ctaButton: "Décrire le besoin",
    },
    services: {
      kicker: "Services & méthode",
      title: "Concevoir. Développer. Mettre en ligne.",
      intro: "Le niveau de conception dépend de la complexité, des utilisateurs, des fonctionnalités et des contraintes. Seul le nécessaire est retenu jusqu’à la mise en ligne.",
      commitmentsKicker: "Périmètre d’intervention",
      commitmentsTitle: "De l’analyse à la livraison.",
      commitments: [
        ["Conception", "Besoin, utilisateurs, priorités, parcours et interfaces."],
        ["Développement", "Architecture, composants, fonctionnalités, responsive et tests."],
        ["Mise en ligne", "Recette, déploiement, contrôles finaux et repères de prise en main."],
      ],
      offersKicker: "Offres",
      offersTitle: "Quatre niveaux d’intervention.",
      productKicker: "Produit numérique",
      productTitle: "Exploration et développement.",
      productIntro: "L’exploration structure une idée encore incomplète. L’application transforme un périmètre validé en produit fonctionnel.",
      productBridge: "La feuille de route sert de base à la conception. Un besoin déjà structuré peut entrer directement en développement.",
      productPriceNote: "* Le package comprend l’exploration et la feuille de route. Des interventions séparées restent possibles, dont la préparation technique à partir de 300 €. Le rôle de partenaire technique pendant la recherche de financement fait l’objet d’un devis distinct.",
      websiteKicker: "Sites vitrines",
      websiteTitle: "Structure essentielle ou conception sur mesure.",
      websiteIntro: "Le niveau d’intervention dépend des contenus disponibles, du nombre de parcours et du degré de personnalisation attendu.",
      websitePriceNote: "* Le tarif dépend du périmètre, des contenus et des fonctionnalités. Le devis peut répartir le paiement entre la conception, le développement et la mise en ligne.",
      methodKicker: "Processus",
      methodTitle: "Des décisions validées avant leur traduction technique.",
      methodOffersLabel: "Offres concernées",
      networkKicker: "Compétences complémentaires",
      networkTitle: "Expertise tierce mobilisable selon le besoin.",
      network: ["Un spécialiste peut intervenir après validation : design, sécurité, marketing, SEO ou autre expertise identifiée. Sa prestation est intégrée au devis global ou contractualisée séparément.", "La maintenance et les évolutions sont réalisées ponctuellement sur devis, sans abonnement obligatoire."],
      ctaTitle: "Identifier l’intervention adaptée.",
      ctaText: "Le formulaire rassemble les informations nécessaires à une première analyse.",
      ctaButton: "Décrire le projet",
    },
    projects: {
      kicker: "Réalisations",
      title: "Problème. Décisions. Solution.",
      intro: "Chaque étude présente le contexte, le périmètre, les choix de conception et la réalisation technique.",
      studyButton: "Consulter l’étude",
      liveButton: "Ouvrir le projet",
    },
    caseUi: {
      openProject: "Ouvrir le projet",
      openStudy: "Lire l’étude ↓",
      status: "Statut",
      role: "Mon rôle",
      duration: "Durée",
      audience: "Usage observé",
      value: "Valeur estimée",
      contextKicker: "Contexte",
      contextTitle: "Situation initiale.",
      challengeKicker: "Problème",
      challengeTitle: "Objectif à atteindre.",
      decisionsKicker: "Décisions",
      decisionsTitle: "Choix de conception.",
      highlights: "Repères",
      interface: "Interface",
      motion: "Parcours",
      motionTitle: "Démonstration fonctionnelle.",
      testimonialKicker: "Témoignage",
      testimonialTitle: "Retour de la cliente.",
      result: "Résultat",
      next: "Évolution prévue",
      stack: "Technologies",
      repository: "Consulter le dépôt GitHub ↗",
      ctaKicker: "Nouveau projet",
      ctaText: "Une question, une idée ou un besoin défini peuvent constituer le point de départ.",
      ctaButton: "Présenter le besoin",
      back: "← Réalisations",
    },
    contact: {
      kicker: "Contact",
      title: "Question ou projet.",
      intro: "Utilise le message libre pour une demande d’information. Utilise le questionnaire pour présenter un projet.",
      inquiryKicker: "Renseignement",
      inquiryTitle: "Poser une question.",
      inquiryText: "Un formulaire court pour obtenir une information sans initier de projet.",
      inquiryButton: "Écrire un message",
      projectKicker: "Projet",
      projectTitle: "Présenter un besoin.",
      projectText: "Le questionnaire fournit les éléments nécessaires à une première analyse.",
      projectButton: "Ouvrir le questionnaire",
      freeKicker: "Message",
      freeTitle: "Votre question.",
      freeText: "Demande d’information, service ou premier échange.",
      formKicker: "Questionnaire",
      formTitle: "Définir le point de départ.",
      formText: "Durée estimée : 8 minutes. Les réponses servent à préparer le premier échange.",
    },
  },
};

export const themedMethodCopy = {
  accueillant: [
    ["Comprendre", "Ton activité, ton idée, les personnes concernées et ce qui rend ce projet important pour toi."],
    ["Donner un cadre", "Mettre des repères autour de l’idée, choisir les priorités et garder le reste pour plus tard."],
    ["Imaginer", "Faire prendre forme aux contenus, aux parcours et à une identité fidèle à ton univers."],
    ["Développer", "Transformer les choix validés en une solution claire, fiable et faite sur mesure."],
    ["Tester", "Parcourir chaque écran, corriger ce qui gêne et vérifier que chacun peut utiliser la solution."],
    ["Mettre en ligne", "Préparer le lancement et te transmettre des repères simples pour la suite."],
  ],
  affirme: [
    ["Analyser", "Identifier l’objectif, les utilisateurs, les contraintes et le véritable levier du projet."],
    ["Prioriser", "Fixer le périmètre, arbitrer les fonctionnalités et verrouiller une première version réaliste."],
    ["Concevoir", "Structurer les parcours, l’information et la direction visuelle avant d’écrire le code."],
    ["Développer", "Exécuter les décisions dans une architecture robuste, lisible et prête à évoluer."],
    ["Éprouver", "Tester les usages, les écrans, les erreurs et corriger tout ce qui fragilise l’expérience."],
    ["Déployer", "Valider la préproduction, mettre en ligne et définir les prochaines évolutions."],
  ],
  minimaliste: [
    ["Comprendre", "Objectifs, utilisateurs, contexte, contraintes."],
    ["Cadrer", "Périmètre, priorités, première version."],
    ["Concevoir", "Contenus, parcours, interfaces, identité."],
    ["Développer", "Architecture, composants, fonctionnalités."],
    ["Tester", "Responsive, accessibilité, erreurs, recette."],
    ["Mettre en ligne", "Préproduction, validation, déploiement, prise en main."],
  ],
};

export const themedCaseCopy = {
  "the-code-of-sp": {
    accueillant: { hook: "Trois sensibilités, une même attention portée à ton projet.", summary: "Un portfolio qui accueille chaque visiteur dans l’univers où il se sent le plus à l’aise.", context: "The Code of SP a été pensé pour présenter mon travail tout en laissant ressentir l’attention que je porte à la personnalité, aux mots et aux intentions qui entourent chaque projet.", challenge: "Créer une rencontre personnelle, où le visiteur peut choisir la manière dont il souhaite découvrir mon travail sans perdre les informations essentielles.", response: "Une entrée inspirée d’une recherche invite à choisir un univers Accueillant, Affirmé ou Minimaliste. La structure reste familière ; le ton, les formes et le rythme s’ajustent à la sensibilité choisie.", result: "Une expérience qui montre, avec simplicité, qu’un même savoir-faire peut écouter et respecter des personnalités différentes.", closing: "Le portfolio ne se contente pas de parler d’adaptation : il laisse chacun en faire l’expérience dès son arrivée.", cta: "Imaginer une identité numérique qui te ressemble" },
    affirme: { hook: "Trois directions. Une expertise qui sait changer de registre.", summary: "Un portfolio conçu comme une démonstration immédiate de positionnement, d’adaptation et de maîtrise technique.", context: "Le portfolio devait aller au-delà d’une liste de compétences : il devait prouver ma capacité à transformer une personnalité de marque en expérience complète.", challenge: "Faire du portfolio une preuve active : capter l’attention, affirmer le positionnement et démontrer l’adaptation avant même la première étude de cas.", response: "Le visiteur choisit entre trois univers complets dès l’entrée. Chaque direction impose son vocabulaire, ses formes, ses animations et son énergie, tout en conservant la même architecture commerciale.", result: "Une vitrine qui ne promet pas l’adaptation : elle l’exécute en direct et transforme la navigation en démonstration de savoir-faire.", closing: "Le site montre concrètement ce que The Code of SP est capable de décider, concevoir et coder.", cta: "Donner à ton identité une direction forte" },
  },
  "manon-pontasse": {
    accueillant: { hook: "Aider chaque personne à trouver des mots qui la rassurent et des repères qui lui parlent.", summary: "Un site doux et accessible qui fait le premier pas vers les personnes accompagnées, leurs proches et les partenaires.", context: "Manon accueille des personnes dont les questions, les émotions et la connaissance de l’accompagnement peuvent être très différentes. Chacune doit pouvoir se sentir reconnue sans être enfermée dans un vocabulaire professionnel.", challenge: "Créer un espace rassurant qui guide sans infantiliser, informe sans alourdir et préserve la chaleur de l’accompagnement proposé par Manon.", response: "Le visiteur choisit son profil et reçoit des premiers repères adaptés. Les contenus pédagogiques, l’approche et le contact prolongent cette attention dans une identité douce et cohérente.", result: "Une présence professionnelle qui rapproche Manon de ses publics et rend son accompagnement plus simple à comprendre.", closing: "Le site ne demande pas aux visiteurs de maîtriser les bons termes : il choisit de venir à leur rencontre.", cta: "Créer un site qui accueille vraiment tes publics" },
    affirme: { hook: "Trois publics. Un parcours clair pour chacun.", summary: "Une vitrine structurée pour orienter rapidement les personnes accompagnées, les proches et les partenaires sociaux.", context: "Trois catégories de visiteurs arrivent avec des niveaux d’information et des objectifs distincts. Un discours unique risquait de diluer le message et de ralentir la prise de contact.", challenge: "Segmenter l’expérience sans fragmenter le site, puis rendre une activité spécialisée immédiatement compréhensible.", response: "Un sélecteur de profil adapte l’introduction, la page Mon approche et les motifs de contact. L’architecture hiérarchise les informations et conduit chaque public vers la bonne réponse.", result: "Un site plus lisible, plus crédible et mieux armé pour convertir des recherches différentes en échanges qualifiés.", closing: "Le parcours assume un principe simple : le bon message, au bon public, au bon moment.", cta: "Structurer un site autour de tes vrais publics" },
  },
  "the-quiz-of-sp": {
    accueillant: { hook: "Faire connaissance en jouant, une question après l’autre.", summary: "Un quiz personnel et vivant qui transforme mes goûts en une petite expérience à partager.", context: "Je cherchais une façon plus spontanée de parler de ce que j’aime qu’une page À propos traditionnelle. Les questions sont devenues un prétexte ludique pour créer une rencontre.", challenge: "Donner envie de rester jusqu’à la fin tout en gardant des règles simples, une progression rassurante et assez de surprise pour sourire à chaque nouvelle partie.", response: "Trois niveaux accompagnent progressivement le joueur, avec des retours visuels, des sons et un choix final : conserver son score ou tenter le quitte ou double.", result: "Une expérience légère en apparence, mais pensée dans chaque détail pour être claire, amusante et rejouable.", closing: "Ce quiz montre qu’un projet personnel peut devenir un vrai terrain d’expérimentation, sans perdre sa spontanéité.", cta: "Donner vie à une idée qui te tient à cœur" },
    affirme: { hook: "170 questions. Trois niveaux. Un choix final qui peut tout changer.", summary: "Un produit arcade full-stack qui transforme une présentation personnelle en défi rejouable.", context: "Une page À propos aurait livré l’information sans engagement. Le quiz devait provoquer une action, installer un rythme et donner une raison d’aller jusqu’au bout.", challenge: "Créer une boucle de jeu comprise en quelques secondes, capable de maintenir la tension jusqu’au boss final et d’assurer un classement fiable.", response: "Progression en trois niveaux, timer, feedback immédiat, sons et mécanique Quitte ou double structurent l’expérience. L’API recalcule les scores avant chaque enregistrement.", result: "Un jeu complet, de l’interface à la base de données, qui prouve autant la conception produit que l’exécution full-stack.", closing: "Le concept est simple. Son traitement est complet : règles, données, sécurité du score, rythme et identité.", cta: "Transformer ton concept en produit interactif" },
  },
  stratusse: {
    accueillant: { hook: "Offrir un endroit où les pensées peuvent être déposées, lues et respectées.", summary: "Une plateforme d’écriture imaginée comme un espace attentif, avec des règles et une modération qui protègent les personnes.", context: "Certaines pensées ont besoin d’un endroit où exister sans être réduites à une publication rapide. Stratusse est né de l’envie de créer cet espace, tout en prenant au sérieux la vulnérabilité qui accompagne parfois l’écriture.", challenge: "Permettre l’expression et la rencontre sans oublier ce qu’un commentaire, un rôle mal compris ou une modération tardive peut provoquer chez une personne qui partage un texte intime.", response: "Des rôles lisibles, des parcours de publication encadrés et une administration dédiée à la modération installent un équilibre entre liberté d’expression et attention portée aux auteurs.", result: "Une plateforme communautaire complète dont l’architecture technique soutient une intention profondément humaine.", closing: "La technique n’est pas placée autour de la communauté : elle est pensée pour prendre soin de son fonctionnement.", cta: "Construire une communauté avec attention et responsabilité" },
    affirme: { hook: "Publier librement. Modérer clairement. Protéger la communauté.", summary: "Une plateforme full-stack où rôles, sécurité et administration rendent l’expression possible à grande échelle.", context: "Créer un espace de publication ne suffit pas. Dès qu’une communauté échange autour de textes personnels, les permissions, la modération et la traçabilité deviennent des fonctions centrales du produit.", challenge: "Concilier liberté de contribution, protection des auteurs, contrôle administratif et évolutivité sans ralentir l’expérience utilisateur.", response: "L’architecture combine authentification, rôles, validation des contenus, modération et journalisation. Chaque fonction répond à un risque concret du parcours communautaire.", result: "Un produit complet qui démontre une maîtrise du front, de l’API, de la sécurité et des enjeux opérationnels d’une communauté.", closing: "Stratusse transforme une intention éditoriale en système robuste, administrable et prêt à évoluer.", cta: "Faire passer une communauté de l’idée au produit" },
  },
  "projet-en-cours": {
    accueillant: { hook: "Faire grandir une idée importante, étape après étape, sans dévoiler ce qui doit encore être protégé.", summary: "Un projet confidentiel accompagné avec patience, structuré en blocs et validé au fil des échanges.", context: "Le projet garde encore son nom, ses écrans et ses fonctionnalités à l’abri des regards. Il permet néanmoins de raconter une collaboration : écouter un besoin qui évolue, accueillir les nouvelles idées et préserver une direction commune.", challenge: "Faire grandir la vision sans brusquer les décisions, tout en distinguant ce qui est déjà construit, ce qui demande encore une validation et ce qui viendra plus tard.", response: "Une feuille de route par blocs rend chaque étape visible et permet de présenter, discuter puis valider les choix avant de poursuivre le développement.", result: "Une plateforme déjà conséquente, construite progressivement dans un cadre qui respecte à la fois l’ambition et le temps de la décision.", closing: "Même sans dévoiler l’interface, le projet raconte une capacité essentielle : accompagner une vision jusqu’à ce qu’elle puisse devenir un produit cohérent.", cta: "Faire grandir une idée complexe avec méthode" },
    affirme: { hook: "Une demande initiale. Un potentiel plus vaste. Une plateforme en construction.", summary: "Un projet confidentiel piloté comme un produit : vision, blocs prioritaires, validations et architecture full-stack.", context: "La demande de départ ciblait une fonctionnalité. L’analyse a révélé un système plus large, plusieurs publics et des parcours interdépendants. L’interface reste confidentielle, pas l’ampleur du travail.", challenge: "Élargir le produit sans perdre le contrôle du périmètre, séparer le développé du validé et maintenir une progression mesurable.", response: "Le projet est découpé en blocs priorisés. Chaque version intermédiaire déclenche des décisions explicites avant d’engager la suivante.", result: "Une architecture full-stack ambitieuse, pilotée avec une logique produit et rendue démontrable sans compromettre sa confidentialité.", closing: "Ce projet prouve une capacité à voir au-delà de la demande, structurer l’ambition et tenir la trajectoire.", cta: "Transformer une ambition complexe en roadmap exécutable" },
  },
};

export function getThemeCopy(theme) {
  return themedPageCopy[normalizeTheme(theme)];
}

export function getThemedCase(project, theme) {
  const voice = themedCaseCopy[project.slug]?.[normalizeTheme(theme)] || {};
  return { ...project, ...voice };
}

export function getThemedMethod(theme) {
  return themedMethodCopy[normalizeTheme(theme)];
}
